
name: receiptor
description: App to upload receipt and get it analysed
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  go_router: ^14.2.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  permission_handler: ^10.4.0
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  freezed: ^2.5.2

flutter:
  uses-material-design: true
